spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/postgres?currentSchema=public
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  liquibase:
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: public

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none