spring:
  datasource:
    url: ${CONNECTION_STRING:jdbc:postgresql://localhost:5432/postgres}?currentSchema=public
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  mvc:
    static-path-pattern: /resource/**
  web:
    resources:
      static-locations:
        - file:src/main/resources/static/
        - classpath:/static/

  liquibase:
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: public
    url: ${CONNECTION_STRING:jdbc:postgresql://localhost:5432/postgres}
    password: postgres
    user: postgres

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
