version: '2'

services:
  app:
    image: 'waffles:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    links:
      - "db:db"
    ports:
      - "8080:8080"
    environment:
      - CONNECTION_STRING=jdbc:postgresql://db:5432/postgres
      - cloudinary_api_name='salat23'
      - cloudinary_api_secret='UPmhbfKuSwyyG3XnKGm7ACrRUNg'
      - cloudinary_api_key='589264481424898'
    networks:
      - waffles
      - externalnetwork
  db:
    image: 'postgres:13.1-alpine'
    container_name: db

    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - waffles
networks:
  waffles:
    internal: true
    driver: bridge
  externalnetwork:
    internal: false